add musicbrainz api
wuvt/notecharlie pull request #1
Opened 2020-11-11 21:26 UTC by paulwalko

@echarlie

2020-11-11 21:34 UTC, echarlie requested changes

2020-11-11 21:34 UTC, echarlie commented on modules/musicbrainz.py
> +#!/usr/bin/env python
python3

2020-11-11 21:34 UTC, echarlie commented on modules/musicbrainz.py
> +def mz(phenny, input):
.mb or .mbz instead.

2020-11-11 21:34 UTC, echarlie commented on modules/test/test_musicbrainz.py
> +    def test_mz_artist(self):
Use a better-known/less likely to be changed artist. e.g. the Beatles.

2020-11-11 21:34 UTC, echarlie commented on modules/musicbrainz.py
> +mz.example = ".mz artist electrobro"
example should use something well-known.

2020-11-21 22:43 UTC, mutantmonkey approved these changes

2020-12-10 03:08 UTC, paulwalko commented
@echarlie

2020-12-10 03:10 UTC, echarlie commented on modules/test/test_musicbrainz.py
> +        input = Mock(group=lambda x: "area Blacksburg")
probably not ideal, b/c Blacksburg, NC exists. But not blocking.

2020-12-10 03:11 UTC, paulwalko commented on modules/test/test_musicbrainz.py
> +        input = Mock(group=lambda x: "area Blacksburg")
SC, actually

2020-12-10 03:11 UTC, echarlie approved these changes
I don't love the test cases, still. but approved.

2020-12-10 03:12 UTC, mutantmonkey commented on modules/test/test_musicbrainz.py
> +        input = Mock(group=lambda x: "area Blacksburg")
Chicago, New York, Portland, San Francisco, San Diego, or Seattle might be good alternatives

2020-12-10 03:17 UTC, paulwalko commented on modules/test/test_musicbrainz.py
> +        self.phenny.say.assert_called_once_with("Top recording for \"basketball\": https://musicbrainz.org/recording/b23393e7-3930-4687-b94b-970982d003e6")
will change

2020-12-10 03:17 UTC, paulwalko commented on modules/test/test_musicbrainz.py
> +        self.phenny.say.assert_called_once_with("404, Song: https://musicbrainz.org/work/18a04f67-f105-42a5-9e6a-10bf349e5965")
will change

2020-12-10 03:17 UTC, paulwalko commented on modules/test/test_musicbrainz.py
> +        self.phenny.say.assert_called_once_with("HELLO,HELLO,HELLO, Album: https://musicbrainz.org/release-group/ef20be97-cfb2-42f9-8a66-f650118c02e4")
will change

2020-12-10 03:17 UTC, paulwalko commented on modules/test/test_musicbrainz.py
> +        self.phenny.say.assert_called_once_with("Blacksburg, City: https://musicbrainz.org/area/76d1e078-7861-4329-8553-f047b922c4f7")
will change

2020-12-12 23:45 UTC, mutantmonkey approved these changes

2020-12-12 23:45 UTC, mutantmonkey commented on modules/test/test_musicbrainz.py
> +        input = Mock(group=lambda x: "recording Never Gonna Give You Up")
:laughing:

2020-12-13 00:15 UTC, merged

2020-12-13 00:38 UTC, mutantmonkey commented
Thanks; this is a great addition!